import {
  AlignBottomIcon,
  AlignHorizontalIcon,
  AlignLeftIcon,
  AlignRightIcon,
  AlignTopIcon,
  AlignVerticalIcon,
  BgIcon,
  BrushIcon,
  Close2Icon,
  CloseIcon,
  CopyIcon,
  Grid1Icon,
  Grid3Icon,
  ImageIcon,
  LockIcon,
  RedoIcon,
  ShapesIcon,
  TextIcon,
  TrashIcon,
  UndoIcon,
  UnlockIcon,
  ZoomInIcon,
  ZoomOutIcon,
} from '@/icons';

export const iconComponents: { [key: string]: React.ComponentType } = {
  grid1Icon: Grid1Icon,
  zoomInIcon: ZoomInIcon,
  zoomOutIcon: ZoomOutIcon,
  imageIcon: ImageIcon,
  bgIcon: BgIcon,
  textIcon: TextIcon,
  grid3Icon: Grid3Icon,
  shapesIcon: ShapesIcon,
  closeIcon: CloseIcon,
  close2Icon: Close2Icon,
  lockIcon: LockIcon,
  unlockIcon: UnlockIcon,
  undoIcon: UndoIcon,
  redoIcon: RedoIcon,
  trashIcon: TrashIcon,
  copyIcon: CopyIcon,
  alignLeftIcon: AlignLeftIcon,
  alignBottomIcon: AlignBottomIcon,
  alignTopIcon: AlignTopIcon,
  alignRightIcon: AlignRightIcon,
  alignHorizontalIcon: AlignHorizontalIcon,
  alignVerticalIcon: AlignVerticalIcon,
  brushIcon: BrushIcon,
};
