import {
  AddImageIcon,
  AlignBottomIcon,
  AlignHorizontalIcon,
  AlignLeftIcon,
  AlignRightIcon,
  AlignTopIcon,
  AlignVerticalIcon,
  ArrowDownIcon,
  ArrowSwapXIcon,
  ArrowSwapYIcon,
  ArrowUpIcon,
  BgIcon,
  Brush2Icon,
  BrushIcon,
  Close2Icon,
  CloseIcon,
  CopyIcon,
  Grid1Icon,
  Grid3Icon,
  ImageIcon,
  LayerIcon,
  LockIcon,
  PositionIcon,
  RedoIcon,
  SettingsIcon,
  ShadowIcon,
  ShapesIcon,
  TextIcon,
  TrashIcon,
  UndoIcon,
  UnlockIcon,
  ZoomInIcon,
  ZoomOutIcon,
} from '@/icons';

export const IconComponents: { [key: string]: React.ComponentType } = {
  grid1Icon: Grid1Icon,
  zoomInIcon: ZoomInIcon,
  zoomOutIcon: ZoomOutIcon,
  imageIcon: ImageIcon,
  bgIcon: BgIcon,
  textIcon: TextIcon,
  grid3Icon: Grid3Icon,
  shapesIcon: ShapesIcon,
  closeIcon: CloseIcon,
  close2Icon: Close2Icon,
  lockIcon: LockIcon,
  unlockIcon: UnlockIcon,
  undoIcon: UndoIcon,
  redoIcon: RedoIcon,
  trashIcon: TrashIcon,
  copyIcon: CopyIcon,
  alignLeftIcon: AlignLeftIcon,
  alignBottomIcon: AlignBottomIcon,
  alignTopIcon: AlignTopIcon,
  alignRightIcon: AlignRightIcon,
  alignHorizontalIcon: AlignHorizontalIcon,
  alignVerticalIcon: AlignVerticalIcon,
  brushIcon: BrushIcon,
  brush2Icon: Brush2Icon,
  positionIcon: PositionIcon,
  shadowIcon: ShadowIcon,
  layerIcon: LayerIcon,
  arrowSwapXIcon: ArrowSwapXIcon,
  arrowSwapYIcon: ArrowSwapYIcon,
  arrowUpIcon: ArrowUpIcon,
  arrowDownIcon: ArrowDownIcon,
  settingsIcon: SettingsIcon,
  addImageIcon: AddImageIcon,
};
